name       : mokutil
version    : 0.6.0
release    : 2
source     :
    - https://github.com/lcp/mokutil/archive/refs/tags/0.6.0.tar.gz : 6cc4be216ac083ee19dc986e8a510e1d74f6f4080baa4b5fdc7c503eb483f569
license    : GPL-3.0-or-later
component  : system.boot
summary    : Utility to manipulate machine owner keys
description: |
    Utility to manipulate machines owner keys managed in shim
builddeps  :
    - pkgconfig(efivar)
    - pkgconfig(libkeyutils)
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
